### ISSUE TITLE
Setting <mongo.path> does not work

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/sample-acmegifts#12]
Set `<mongo.path>/Users/fmhwong/mongodb-osx-x86_64-3.6.5</mongo.path>` in pom.xml.
Run `mvn clean install` and tests failed.

Liberty messages.log showed:
```
[19/06/18 15:33:39:124 EDT] 00000044 com.mongodb.driver.cluster I Exception in monitor 
thread while connecting to server localhost:5052
com.mongodb.MongoException$Network: Exception opening the socket	
  at com.mongodb.DBPort.<init>(DBPort.java:117)	
  at com.mongodb.DBPort.<init>(DBPort.java:100)	
  at com.mongodb.ServerMonitor$ServerMonitorRunnable.run(ServerMonitor.java:89)	
  at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused (Connection refused)	
  at java.net.PlainSocketImpl.socketConnect(Native Method)	
  at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)	
  at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)	
  at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)	
  at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)	
  at java.net.Socket.connect(Socket.java:589)	
  at com.mongodb.DBPort.ensureOpen(DBPort.java:292)	
  at com.mongodb.DBPort.<init>(DBPort.java:113)	
  ... 3 more
```

**Comment by mezarin** [comment]
Hi, Thanks for reporting this issue. The path as originally required is the path to the MongoDB installation's bin directory. So, you would need to set it to something like this:  <mongo.path>/Users/fmhwong/mongodb-osx-x86_64-3.6.5/bin</mongo.path>.

Having said that, there is still an issue where the specified path is not set properly.
